import React,{useEffect,useState} from 'react';import{createRoot}from'react-dom/client';import{Upload,Search,ThumbsUp,ThumbsDown,Download,LogOut,ShieldCheck,Flag,Sparkles,Loader2,Trash2}from'lucide-react';import'./style.css';
const api=async(path,opt={})=>{const r=await fetch(path,{credentials:'include',...opt});const j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error||'Request failed');return j};
function Auth({meta,onDone}){const[mode,setMode]=useState('login'),[f,setF]=useState({username:'',password:'',course:meta.courses[0],semester:1}),[err,setErr]=useState('');async function go(){try{await api('/api/auth/'+(mode==='login'?'login':'register'),{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(f)});onDone()}catch(e){setErr(e.message)}}return <div className="center"><div className="auth card"><h1>Prior Art</h1><p>Student resources, organized by course and semester.</p><input placeholder="Username" value={f.username} onChange={e=>setF({...f,username:e.target.value})}/><input type="password" placeholder="Password (8+ chars)" value={f.password} onChange={e=>setF({...f,password:e.target.value})}/><select value={f.course} onChange={e=>setF({...f,course:e.target.value})}>{meta.courses.map(x=><option>{x}</option>)}</select><select value={f.semester} onChange={e=>setF({...f,semester:+e.target.value})}>{meta.semesters.map(x=><option value={x}>Semester {x}</option>)}</select>{err&&<div className="error">{err}</div>}<button className="primary" onClick={go}>{mode==='login'?'Log in':'Create account'}</button><button className="link" onClick={()=>setMode(mode==='login'?'register':'login')}>{mode==='login'?'Create an account':'Back to login'}</button></div></div>}
function App(){const[meta,setMeta]=useState(null),[me,setMe]=useState(null),[tab,setTab]=useState('browse');useEffect(()=>{api('/api/meta').then(setMeta);api('/api/me').then(setMe).catch(()=>{})},[]);if(!meta)return <div className="center"><Loader2/></div>;if(!me)return <Auth meta={meta} onDone={()=>api('/api/me').then(setMe)}/>;return <><header><b>Prior Art</b><nav>{['browse','upload','profile'].map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)}>{x}</button>)}{me.is_admin?<button className={tab==='admin'?'active':''} onClick={()=>setTab('admin')}>admin</button>:null}</nav><span>⭐ {me.karma} · {me.username} <button onClick={async()=>{await api('/api/auth/logout',{method:'POST'});location.reload()}}><LogOut size={15}/></button></span></header><main>{tab==='browse'?<Browse meta={meta} me={me}/>:tab==='upload'?<UploadTab meta={meta} me={me}/>:tab==='profile'?<Profile/>:<Admin/>}</main></>}
function Browse({meta,me}){const[rows,setRows]=useState([]),[q,setQ]=useState(''),[ai,setAi]=useState(''),[loading,setLoading]=useState(false),[selected,setSelected]=useState(null),[filters,setFilters]=useState({subject:'All',contentType:'All',examType:'All'});async function load(){const p=new URLSearchParams({q,...filters});setRows(await api('/api/resources?'+p.toString()))}useEffect(()=>{load()},[]);async function ask(){setLoading(true);try{const r=await api('/api/ai/search',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({query:ai})});setRows(r.matchedIds.length?await Promise.all(r.matchedIds.map(id=>api('/api/resources/'+id))):[]);alert(r.summary||'')}catch(e){alert(e.message)}finally{setLoading(false)}}return <section><div className="hero"><div><p className="eyebrow">YOUR ACADEMIC LIBRARY</p><h2>Find the material you need.</h2><p className="muted">Browse by semester, search normally, or ask AI to narrow it down.</p></div></div><div className="filters"><select value={filters.subject} onChange={e=>setFilters({...filters,subject:e.target.value})}><option value="All">All subjects</option>{(meta.subjectsByCourse?.[me.course]||[]).map(x=><option key={x} value={x}>{x}</option>)}</select><select value={filters.contentType} onChange={e=>setFilters({...filters,contentType:e.target.value})}><option>All</option>{meta.contentTypes.map(x=><option key={x}>{x}</option>)}</select><select value={filters.examType} onChange={e=>setFilters({...filters,examType:e.target.value})}><option>All</option>{meta.examTypes.map(x=><option key={x}>{x}</option>)}</select><button onClick={load}>Apply</button></div><div className="search"><Search/><input placeholder="Search resources" value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load()}/><button onClick={load}>Search</button></div><div className="ai"><Sparkles/><input placeholder="Ask: DBMS mid-sem PYQs from 2022–2025" value={ai} onChange={e=>setAi(e.target.value)} onKeyDown={e=>e.key==='Enter'&&ask()}/><button onClick={ask} disabled={loading}>Ask AI</button></div><div className="result-count">{rows.length} resource{rows.length===1?'':'s'} found</div><div className="grid">{rows.map(r=><article className="card" onClick={()=>setSelected(r)}><small>{r.content_type} · {r.subject} · {r.paper_year}</small><h3>{r.title}</h3><p>{r.excerpt}</p><div>👍 {r.up} · 👎 {r.down} · {r.downloads} downloads</div></article>)}</div>{selected&&<Detail r={selected} close={()=>setSelected(null)} refresh={load}/>}</section>}
function Detail({r,close,refresh}){const[reason,setReason]=useState('');async function vote(type){await api('/api/resources/'+r.id+'/vote',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({type})});refresh()}async function download(){const resp=await fetch('/api/resources/'+r.id+'/download',{method:'POST',credentials:'include'});const j=await resp.json().catch(()=>({}));if(!resp.ok){alert(j.error||'Download failed');return}if(j.url){window.location.href=j.url;return}alert('Download started')}async function report(){if(!reason)return;await api('/api/resources/'+r.id+'/report',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({reason})});setReason('');alert('Report submitted')}return <div className="modal"><div className="modalbox"><button className="close" onClick={close}>×</button><h2>{r.title}</h2><p>{r.excerpt}</p><div className="actions"><button onClick={()=>vote('up')}><ThumbsUp/></button><button onClick={()=>vote('down')}><ThumbsDown/></button><button className="primary" onClick={download}><Download/> Download</button></div><hr/><input placeholder="Report reason" value={reason} onChange={e=>setReason(e.target.value)}/><button onClick={report}><Flag/> Report</button></div></div>}
function UploadTab({meta,me}){
 const[file,setFile]=useState(null),[title,setTitle]=useState(''),[busy,setBusy]=useState(false),[draft,setDraft]=useState(null),[form,setForm]=useState({subject:'',contentType:'Notes',examType:'',paperYear:'',professor:''});
 const subjects=meta.subjectsByCourse?.[me.course]||[];
 useEffect(()=>{setForm(f=>({...f,subject:f.subject||subjects[0]||''}))},[subjects.join('|')]);
 async function submit(){if(!file)return;setBusy(true);const fd=new FormData();fd.append('file',file);fd.append('title',title);try{const queued=await api('/api/resources',{method:'POST',body:fd});let job=queued;while(job.status==='processing'||job.status==='queued'){await new Promise(r=>setTimeout(r,1200));job=await api('/api/jobs/'+queued.jobId)}if(job.status!=='completed')throw new Error(job.error||'Upload processing failed');setDraft({id:job.resourceId,analysis:job.analysis,duplicateCandidates:job.duplicateCandidates});setForm({subject:job.analysis?.subject&&job.analysis.subject!=='UNSURE'?job.analysis.subject:(subjects[0]||''),contentType:job.analysis?.contentType||'Notes',examType:job.analysis?.examType||'',paperYear:job.analysis?.paperYear||'',professor:job.analysis?.professor||''});setFile(null);setTitle('')}catch(e){alert(e.message)}finally{setBusy(false)}}
 async function publish(){if(!draft)return;setBusy(true);try{await api('/api/resources/'+draft.id+'/publish',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...form,title:title||draft.analysis?.suggestedTitle||'Untitled resource'})});setDraft(null);alert('Published successfully. You earned 10 karma.')}catch(e){alert(e.message)}finally{setBusy(false)}}
 async function reject(){if(!draft)return;await api('/api/resources/'+draft.id+'/reject',{method:'POST'});setDraft(null)}
 return <section><h2>Upload</h2><div className="card form">
  {!draft?<><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Optional title"/><input type="file" accept=".txt,.docx,.pdf,.png,.jpg,.jpeg,.webp" onChange={e=>setFile(e.target.files[0])}/><p>Maximum 20 MB. PDF/images are extracted server-side; scanned PDFs use OCR when Poppler is installed.</p><button className="primary" disabled={!file||busy} onClick={submit}>{busy?<Loader2/>:<Upload/>} {busy?'Processing…':'Upload & analyze'}</button></>:<>
   <div className="success"><Sparkles/> AI analysis complete. Review these fields before publishing.</div>
   {draft.duplicateCandidates?.length>0&&<div className="warning"><b>Possible duplicates found.</b>{draft.duplicateCandidates.map(d=><div key={d.id}>{d.title} · {d.subject} · {d.paperYear||'—'}</div>)}</div>}
   <label>Title<input value={title||draft.analysis?.suggestedTitle||''} onChange={e=>setTitle(e.target.value)}/></label>
   <label>Subject<select value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})}>{subjects.map(x=><option key={x}>{x}</option>)}</select></label>
   <label>Content type<select value={form.contentType} onChange={e=>setForm({...form,contentType:e.target.value})}>{meta.contentTypes.map(x=><option key={x}>{x}</option>)}</select></label>
   {form.contentType==='PYQ'&&<><label>Exam type<select value={form.examType} onChange={e=>setForm({...form,examType:e.target.value})}><option value="">Select</option>{meta.examTypes.map(x=><option key={x}>{x}</option>)}</select></label><label>Paper year<input value={form.paperYear} onChange={e=>setForm({...form,paperYear:e.target.value})} placeholder="2025"/></label></>}
   <label>Professor (optional)<input value={form.professor} onChange={e=>setForm({...form,professor:e.target.value})}/></label>
   <p className="muted">Nothing is published until you confirm. Upload reward: <b>+10 karma</b>.</p><div className="actions"><button onClick={reject}>Discard</button><button className="primary" disabled={busy} onClick={publish}>Confirm & publish</button></div>
  </>}
 </div></section>}
function Profile(){const[d,setD]=useState(null);useEffect(()=>{api('/api/profile').then(setD)},[]);if(!d)return <Loader2/>;return <section><h2>{d.user.username}</h2><p>{d.user.course} · Semester {d.user.semester}</p><div className="stats"><div>⭐ {d.user.karma} karma</div><div>{d.uploads.length} uploads</div><div>{d.user.free_downloads_used}/3 free downloads</div></div><h3>My uploads</h3>{d.uploads.map(x=><div className="list card"><b>{x.title}</b><span>{x.downloads} downloads</span></div>)}<h3>Downloads</h3>{d.downloads.map(x=><div className="list card"><b>{x.title}</b><span>{x.cost?`-${x.cost} karma`:'Free'}</span></div>)}<h3>Karma history</h3>{d.karma.map(x=><div className="list"><span>{x.reason}</span><b>{x.amount>0?'+':''}{x.amount}</b></div>)}</section>}
function Admin(){const[reports,setReports]=useState([]);async function load(){setReports(await api('/api/admin/reports'))}useEffect(()=>{load()},[]);async function act(id,action){await api('/api/admin/reports/'+id,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action})});load()}return <section><h2><ShieldCheck/> Admin</h2>{reports.map(r=><div className="list card"><div><b>{r.title}</b><p>{r.reporter}: {r.reason}</p></div><button onClick={()=>act(r.id,'dismiss')}>Dismiss</button><button className="danger" onClick={()=>act(r.id,'remove')}><Trash2/> Remove</button></div>)}</section>}
createRoot(document.getElementById('root')).render(<App/>);
